### Sudo random number generation
Set seed with random.seed(1)

In [1]:
import random

In [12]:
help(random.randint)

Help on method randint in module random:

randint(a, b) method of random.Random instance
    Return random integer in range [a, b], including both end points.



In [15]:
random.random() # random float (0,1)

0.9833062728745775

In [18]:
random.uniform(0,10) # random float in this range

4.529226249245867

In [24]:
random.randint(0,4) # picks random int in the range

1

In [26]:
random.normalvariate(0,1) # normal mean of 0 sd of 1

-0.04780256143037807

In [35]:
my_list = list('ABCDDD') # pick something from a list
random.choice(my_list)

'D'

In [38]:
random.sample(my_list,k=2)

['C', 'D']

In [40]:
random.choices(my_list,k=3) # can pick elements multiple times

['C', 'A', 'D']

In [49]:
random.shuffle(my_list)
print(my_list)

['D', 'B', 'D', 'D', 'A', 'C']


### We can do random things with numpy arrays as well
We can use the random module in the numpy library

In [50]:
import numpy as np

In [61]:
a = np.random.rand(3)
print(a)

[0.05850232 0.00157015 0.89397903]


In [62]:
a = np.random.rand(3,2)
print(a)

[[0.29106083 0.41008619]
 [0.07405839 0.19317328]
 [0.43344006 0.15161771]]


In [64]:
a =np.random.randint(1,10)
print(a)

2


In [77]:
a =np.random.randint(8,high=10,size=(3,2))
print(a)

[[8 8]
 [8 9]
 [9 9]]
